# shellcheck shell=bash
# lib/client.sh — client keypair, conf writer, QR (terminal ASCII + PNG), base64
[[ -n "${_LIB_CLIENT_LOADED:-}" ]] && return 0
_LIB_CLIENT_LOADED=1

WG_DIR="/etc/wireguard"
WG_CLIENTS_DIR="${WG_DIR}/clients"

# ----- Validate client name (no spaces, no special chars) -----
# Args: name -> exits 1 if invalid
validate_client_name() {
    local name="$1"
    if [[ -z "${name}" ]]; then
        msg_err "Client name cannot be empty"
        return 1
    fi
    if [[ ! "${name}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
        msg_err "Client name must match [a-zA-Z0-9_-]+ (got: '${name}')"
        return 1
    fi
    if [[ ${#name} -gt 32 ]]; then
        msg_err "Client name too long (max 32 chars)"
        return 1
    fi
    return 0
}

# ----- Generate client keypair, write conf -----
# Args: client_name server_public server_endpoint server_subnet server_dns use_psk
# Writes: /etc/wireguard/clients/<name>.conf (chmod 600)
# Returns: 0 on success; client_private/client_public set in caller scope via globals
generate_client() {
    local name="$1"
    local server_public="$2"
    local server_endpoint="$3"
    local subnet="$4"
    local dns="$5"
    local use_psk="${6:-1}"

    if ! validate_client_name "${name}"; then
        return 1
    fi

    local conf_path="${WG_CLIENTS_DIR}/${name}.conf"
    if [[ -f "${conf_path}" && "${DRYRUN:-0}" != "1" ]]; then
        msg_err "Client '${name}' already exists at ${conf_path}"
        return 1
    fi

    # Allocate IP
    local client_ip
    client_ip="$(next_client_ip "${subnet}")"

    # Generate keys (uses gen_keypair from server.sh)
    gen_keypair "CLIENT"
    local priv="${CLIENT_PRIVATE}"
    local pub="${CLIENT_PUBLIC}"
    local psk=""
    if [[ "${use_psk}" == "1" ]]; then
        psk="$(gen_psk)"
    fi

    # In dryrun, do not write the conf (we just want keys + IP for inspection).
    if [[ "${DRYRUN:-0}" == "1" ]]; then
        msg_info "[dryrun] would write ${conf_path} (client ${name}, IP ${client_ip})"
        CLIENT_IP="${client_ip}"
        CLIENT_PRIVATE="${priv}"
        CLIENT_PUBLIC="${pub}"
        CLIENT_PSK="${psk}"
        return 0
    fi

    mkdir -p "${WG_CLIENTS_DIR}"
    chmod 700 "${WG_CLIENTS_DIR}"

    cat > "${conf_path}" <<EOF
# WireGuard client config: ${name}
# Generated by wireguard-vps-installer
[Interface]
PrivateKey = ${priv}
Address = ${client_ip}/32
DNS = ${dns}

[Peer]
PublicKey = ${server_public}
Endpoint = ${server_endpoint}
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
EOF

    if [[ -n "${psk}" ]]; then
        # Insert PSK line after PublicKey
        sed -i.bak "/^PublicKey = ${server_public}$/a\\
PresharedKey = ${psk}" "${conf_path}" && rm -f "${conf_path}.bak"
    fi

    chmod 600 "${conf_path}"
    CLIENT_IP="${client_ip}"
    CLIENT_PRIVATE="${priv}"
    CLIENT_PUBLIC="${pub}"
    CLIENT_PSK="${psk}"
    msg_ok "Generated client '${name}' at ${conf_path} (${client_ip})"
}

# ----- Render terminal ASCII QR code -----
# Args: conf_path
render_qr_terminal() {
    local conf_path="$1"
    if [[ "${DRYRUN:-0}" == "1" ]]; then
        msg_info "[dryrun] would print terminal ASCII QR for ${conf_path}"
        return 0
    fi
    if ! has_cmd qrencode; then
        msg_warn "qrencode not installed — skipping terminal QR"
        return 1
    fi
    echo ""
    qrencode -t ansiutf8 < "${conf_path}"
}

# ----- Render PNG QR code -----
# Args: conf_path output_png
render_qr_png() {
    local conf_path="$1"
    local out_png="$2"
    if [[ "${DRYRUN:-0}" == "1" ]]; then
        msg_info "[dryrun] would write PNG QR to ${out_png}"
        return 0
    fi
    if ! has_cmd qrencode; then
        msg_warn "qrencode not installed — skipping PNG QR"
        return 1
    fi
    # Use level M error correction and explicit 0 (auto) version for better
    # compatibility with mobile WireGuard clients (default L + 0 sometimes
    # produces codes that Android/iOS clients refuse to scan).
    qrencode -t png -l M --level=M -o "${out_png}" < "${conf_path}" || \
    qrencode -t png -o "${out_png}" < "${conf_path}"
    chmod 600 "${out_png}"
    msg_ok "Wrote PNG QR: ${out_png}"
}

# ----- Base64 encode conf (for sharing via terminal paste) -----
# Args: conf_path
render_base64() {
    local conf_path="$1"
    if [[ "${DRYRUN}" == "1" ]]; then
        msg_info "[dryrun] would print base64 of ${conf_path}"
        return 0
    fi
    base64 "${conf_path}"
}

# ----- Full client delivery: writes conf, renders all 3 outputs -----
# Args: client_name server_public server_endpoint subnet dns use_psk
# In dryrun mode, conf is NOT written (caller still gets CLIENT_* globals), but
# QR rendering is skipped entirely (since terminal ASCII would clutter tests).
deliver_client() {
    local name="$1"
    local server_public="$2"
    local server_endpoint="$3"
    local subnet="$4"
    local dns="$5"
    local use_psk="${6:-1}"

    if ! generate_client "${name}" "${server_public}" "${server_endpoint}" "${subnet}" "${dns}" "${use_psk}"; then
        return 1
    fi

    if [[ "${DRYRUN:-0}" == "1" ]]; then
        msg_ok "[dryrun] client '${name}' deliverable built (IP ${CLIENT_IP})"
        return 0
    fi

    local conf_path="${WG_CLIENTS_DIR}/${name}.conf"
    local png_path="${WG_CLIENTS_DIR}/${name}.png"

    render_qr_png "${conf_path}" "${png_path}"

    msg_step "Client '${name}' ready"
    echo ""
    echo "Config file : ${conf_path}"
    echo "PNG QR      : ${png_path}"
    echo ""
    echo "── conf ──────────────────────────────────────────"
    cat "${conf_path}"
    echo "──────────────────────────────────────────────────"
    echo ""

    render_qr_terminal "${conf_path}"
}

# ----- List existing clients (from clients/ dir) -----
list_clients() {
    if [[ ! -d "${WG_CLIENTS_DIR}" ]]; then
        echo "(no clients yet)"
        return 0
    fi
    local found=0
    while IFS= read -r -d '' f; do
        local name
        name="$(basename "${f}" .conf)"
        local ip
        ip="$(grep -E '^Address' "${f}" | awk '{print $3}' || echo '?')"
        printf "  %-24s  %s\n" "${name}" "${ip}"
        found=1
    done < <(find "${WG_CLIENTS_DIR}" -maxdepth 1 -name "*.conf" -type f -print0 2>/dev/null | sort -z)
    if [[ ${found} -eq 0 ]]; then
        echo "(no clients yet)"
    fi
}

# ----- Get client name from conf path -----
client_name_from_path() {
    basename "$1" .conf
}

# ----- Remove client: conf + png + peer from wg0.conf -----
remove_client() {
    local name="$1"

    if [[ "${DRYRUN:-0}" == "1" ]]; then
        msg_info "[dryrun] would remove client '${name}'"
        return 0
    fi

    local conf="${WG_CLIENTS_DIR}/${name}.conf"
    local png="${WG_CLIENTS_DIR}/${name}.png"

    if [[ ! -f "${conf}" ]]; then
        msg_err "Client '${name}' does not exist (no conf at ${conf})"
        return 1
    fi

    remove_peer_from_server "${name}"

    rm -f "${conf}" "${conf}.bak" "${png}"
    msg_ok "Removed client '${name}'"

    # Reload wg-quick so the running interface reflects removal
    if has_cmd systemctl && systemctl is-active --quiet wg-quick@wg0.service 2>/dev/null; then
        systemctl reload wg-quick@wg0.service 2>/dev/null || \
            systemctl restart wg-quick@wg0.service 2>/dev/null || true
    fi
}

# ----- Print current server config summary -----
print_server_summary() {
    local server_pub="$1"
    local listen_port="$2"
    local subnet="$3"
    local dns="$4"
    local endpoint="$5"

    msg_banner "WireGuard Server Configuration"
    printf "  %-18s %s\n" "Server PublicKey:" "${server_pub}"
    printf "  %-18s %s\n" "Endpoint:"        "${endpoint}"
    printf "  %-18s %s\n" "ListenPort:"      "${listen_port}"
    printf "  %-18s %s\n" "Subnet:"          "${subnet}"
    printf "  %-18s %s\n" "DNS:"             "${dns}"
    printf "  %-18s %s\n" "Config:"          "${WG_DIR}/wg0.conf"
    printf "  %-18s %s\n" "Clients dir:"     "${WG_CLIENTS_DIR}"
    printf "  %-18s %s\n" "Service:"         "wg-quick@wg0.service"
}
